config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :cloud_files
  post "/cloud_files/add", to: "cloud_files#add"
  delete "/cloud_files/delete/:id", to: "cloud_files#delete", as: "cloud_files_delete"
  post "/cloud_files/sync/:id", to: "cloud_files#sync", as: "sync_cloud_files"
  post "/cloud_files/cancel_downloads/:id", to: "cloud_files#cancel_downloads", as: "cancel_cloud_file_downloads"
  post "/cloud_files/enqueue_downloads/:id", to: "cloud_files#enqueue_downloads", as: "enqueue_cloud_file_downloads"

  resources :paths
  post "/paths/download/:id", to: "paths#download", as: "download_path"
  post "/paths/cancel_download/:id", to: "paths#cancel_download", as: "cancel_download_path"

  root to: "cloud_files#index"

  mount Sidekiq::Web => '/sidekiq'
end

app/views/shared/_cloud_file.html.erb
<div class="row">
  <div class="col">
    <div class="card">
      <div class="card-body bg-light">
        <h5 class="card-title">Remote</h5>
        <h6 class="card-subtitle mb-2 text-muted">(<%= @cloud_file.remote_percent_complete %>%)</h6>

        <table class="table table-bordered table-striped">
          <tr>
            <td>Remote ID</td>
            <td><%= @cloud_file.remote_id %></td>
          </tr>
          <tr>
            <td>Remote created at</td>
            <td><%= time_ago_in_words(@cloud_file.remote_created_at) %> ago</td>
          </tr>
          <tr>
            <td>Original link</td>
            <td><a href="<%= @cloud_file.original_link %>" class="link-secondary"><%= @cloud_file.original_link.truncate(30) %></a></td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="card">
      <div class="card-body bg-light">
        <h5 class="card-title">Local status</h5>
        <h6 class="card-subtitle mb-2 text-muted">
          <%= @cloud_file.downloadable_paths.select(&:downloaded?).count %> of <%= @cloud_file.downloadable_paths.count %>
          (<%= @cloud_file.percent_complete %>%)
        </h6>

        <table class="table table-bordered table-striped">
          <tr>
            <td>Size</td>
            <td><%= number_to_human_size(@cloud_file.total_downloadable_size) %></td>
          </tr>
          <tr>
            <td>Paths</td>
            <td><%= @cloud_file.paths.count %></td>
          </tr>
          <tr>
            <td>Content type</td>
            <td><%= @cloud_file.content_type %></td>
          </tr>
        </table>
      </div>
    </div>
  </div>

  <div class="col">
  </div>
</div>

app/views/shared/_cloud_files.erb
  <table class="table">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Remote ID</th>
        <th scope="col">Filename</th>
        <th scope="col">Size</th>
        <th scope="col">Complete</th>
        <th scope="col">Remote Complete</th>
        <th scope="col">Content type</th>
        <th scope="col">Status</th>
        <th scope="col">Remote created</th>
        <th scope="col">Files</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @cloud_files.each do |cloud_file| %>
        <% rowclass = cloud_file.percent_complete >= 100 ? "table-success" : "table-light" %>
        <tr scope="row" class="<%= rowclass %>">
          <td><%= cloud_file.id %></td>
          <td><%= cloud_file.remote_id %></td>
          <td><%= link_to cloud_file.filename || "TBD", cloud_file, class: "link-secondary" %></td>
          <td><%= number_to_human_size(cloud_file.total_downloadable_size) %></td>
          <td><%= cloud_file.percent_complete %>%</td>
          <td><%= cloud_file.remote_percent_complete %>%</td>
          <td><%= cloud_file.content_type %></td>
          <td><%= cloud_file.status %></td>
          <td><%= time_ago_in_words(cloud_file.remote_created_at) %> ago</td>
          <td><%= cloud_file.downloadable_paths.count %></td>
          <td>
            <%= button_to 'Delete',
              cloud_files_delete_path(cloud_file),
              method: :delete,
              data: { confirm: 'Are you sure?' },
              class: "btn btn-primary"
            %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

app/views/shared/_header.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light  bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">Getty McGee</a>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/">CloudFiles</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/paths">Paths</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/sidekiq">Sidekiq</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="/admin">Admin</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_path_list.html.erb
<table class="table table-fit">
  <tr>
    <th>ID</th>
    <th>File</th>
    <th>Status</th>
    <th>Downloaded</th>
    <% if @cloud_file %>
      <th width="%1">
        <div class="d-flex">
          <%= button_to 'Download',
            enqueue_cloud_file_downloads_path(@cloud_file),
            disabled: !@cloud_file.paths.any? { |path| path.may_mark_enqueued? },
            class: "btn btn-primary"
          %>
          <%= button_to 'Cancel',
            cancel_cloud_file_downloads_path(@cloud_file),
            disabled: !@cloud_file.paths.any? { |path| path.may_cancel? },
            class: "btn btn-primary"
          %>
        </div>
      </th>
    <% else%>
        <th>Actions</th>
    <% end %>
  </tr>

  <% @paths.order(:id).each do |path| %>
    <% rowclass = (path.percent_complete && path.percent_complete >= 100) ? "table-success" : "table-light" %>
    <% last_error = path.sync_errors.last&.message %>
    <tr scope="row" class="<%= rowclass %>">
      <td><%= path.id %></td>
      <td>
        <a href="<%= path.url %>" class="link-secondary" title="<%= last_error %>"><%= path.path %></a>
        <%= fa_icon "info-circle", title: last_error if last_error %>
      </td>
      <td><%= path.status %></td>
      <td><%= number_to_human_size(path.amount) %> / <%= number_to_human_size(path.size) %> (<%= path.percent_complete %>%)</td>
      <td>
        <div class="d-flex">
          <%= button_to 'Download', download_path_path(path), disabled: !path.may_mark_enqueued?, class: "btn" %>
          <%= button_to 'Cancel', cancel_download_path_path(path), disabled: !path.may_cancel?, class: "btn" %>
        </div>
      </td>
    </tr>
  <% end %>
</table>