config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq/cron/web'

Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :cloud_files
  post "/cloud_files/add", to: "cloud_files#add"
  delete "/cloud_files/delete/:id", to: "cloud_files#delete", as: "cloud_files_delete"
  post "/cloud_files/sync/:id", to: "cloud_files#sync", as: "sync_cloud_files"
  post "/cloud_files/cancel_downloads/:id", to: "cloud_files#cancel_downloads", as: "cancel_cloud_file_downloads"
  post "/cloud_files/enqueue_downloads/:id", to: "cloud_files#enqueue_downloads", as: "enqueue_cloud_file_downloads"

  resources :paths
  post "/paths/download/:id", to: "paths#download", as: "download_path"
  post "/paths/cancel_download/:id", to: "paths#cancel_download", as: "cancel_download_path"

  root to: "cloud_files#index"

  mount Sidekiq::Web => '/sidekiq'
end

app/models/cloud_file.rb
# frozen_string_literal: true

class CloudFile < ApplicationRecord
  VIDEO_EXTENSIONS = %w[mkv mp4 avi m4v webm].freeze
  ATTR_MAPPING = {
    file_name: :filename,
    is_directory: :directory,
    amount: :remote_amount
  }.freeze

  include AASM
  include Failable

  class << self
    def from_object(obj)
      new(
        remote_id: obj.request_id,
        filename: obj.file_name,
        status: obj.status,
        original_link: obj.original_link,
        directory: obj.is_directory,
        remote_created_at: obj.created_on,
        server: obj.server,
        content_type: type_for(obj.file_name)
      )
    end

    def type_for(filename)
      return nil unless filename
      return :tv if filename.match?(/s\d\de\d\d/i) || filename.match?(/season[ _.]?\d/i) || filename.match?(/s\d\d/i)

      :movie
    end
  end

  has_many :paths

  validates :remote_id, presence: true

  enum content_type: %i[tv movie]
  enum status: %i[downloaded downloading created deleted queued canceled]

  aasm column: :status, enum: true do
    state :created, initial: true
    state :queued
    state :downloaded
    state :downloading
    state :deleted
    state :canceled

    event :mark_canceled do
      transitions from: %i[created queued downloading], to: :canceled
    end

    event :mark_deleted do
      transitions from: %i[created downloading downloaded queued canceled], to: :deleted
    end

    event :mark_downloading do
      transitions from: :created, to: :downloading
    end

    event :mark_downloaded do
      transitions from: %i[created downloading], to: :downloaded
    end
  end

  scope :downloaded_without_paths, -> { downloaded.where.missing(:paths) }

  def update_with_object(obj)
    attrs = map_keys(obj.to_h).slice(*attributes.symbolize_keys.keys)
    assign_attributes(attrs)

    self.content_type = CloudFile.type_for(obj.file_name) if obj.file_name
    update_status(obj.status) if obj.status

    save!
  end

  def total_downloadable_size
    downloadable_paths.map(&:size).compact.sum
  end

  def percent_complete
    return 0 if total_downloadable_size.zero?

    (total_downloaded_size.to_f / total_downloadable_size * 100).to_i
  end

  def remote_percent_complete
    return 100 if downloaded?
    return 0 unless file_size&.positive?

    (remote_amount.to_f / file_size * 100).to_i
  end

  def active?
    %w[created downloading].include?(status)
  end

  def downloadable_paths
    @downloadable_paths ||= paths.select(&:downloadable?)
  end

  private

  def total_downloaded_size
    downloadable_paths.map(&:amount).sum
  end

  def map_keys(input_hash)
    input_hash.transform_keys do |key|
      ATTR_MAPPING.include?(key) ? ATTR_MAPPING[key] : key
    end
  end

  def update_status(status)
    public_send(:"mark_#{status}") if respond_to?(:"may_mark_#{status}") && public_send(:"may_mark_#{status}?")
  end
end

app/controllers/cloud_files_controller.rb
# frozen_string_literal: true

class CloudFilesController < ApplicationController
  before_action :set_cloud_file, only: %i[show edit update destroy]

  # GET /cloud_files or /cloud_files.json
  def index
    @cloud_files = CloudFile.order(remote_created_at: :desc)

    @cloud_files = @cloud_files.not_deleted unless params[:show_deleted]
  end

  def show
    @cloud_file = CloudFile.find(params[:id])
    @paths = @cloud_file.paths
  end

  def add
    AddLinkService.new(link: params[:link]).execute

    redirect_to action: "index"
  rescue Offcloud::Client::RequestError => e
    Rails.logger.error(e)
    flash.alert = e

    redirect_to action: "index"
  end

  # POST /cloud_files or /cloud_files.json
  def create
    @cloud_file = CloudFile.new(cloud_file_params)

    respond_to do |format|
      if @cloud_file.save
        format.html { redirect_to @cloud_file, notice: "Cloud file was successfully created." }
        format.json { render :show, status: :created, location: @cloud_file }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @cloud_file.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cloud_files/1 or /cloud_files/1.json
  def update
    respond_to do |format|
      if @cloud_file.update(cloud_file_params)
        format.html { redirect_to @cloud_file, notice: "Cloud file was successfully updated." }
        format.json { render :show, status: :ok, location: @cloud_file }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @cloud_file.errors, status: :unprocessable_entity }
      end
    end
  end

  def delete
    @cloud_file = CloudFile.find(params[:id])
    return if @cloud_file.deleted?

    @cloud_file.mark_deleted!
    DefaultWorker.perform_async(task: "remove_cloud_file", remote_id: @cloud_file.remote_id)

    redirect_to action: "index"
  end

  def destroy
    @cloud_file.destroy
    respond_to do |format|
      format.html { redirect_to cloud_files_url, notice: "Cloud file was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def sync
    @cloud_file = CloudFile.find(params[:id])

    DefaultWorker.perform_async(task: "sync_cloud_file_paths", cloud_file_id: @cloud_file.id) if @cloud_file.downloaded?
    DefaultWorker.perform_async(task: "update_status", cloud_file_id: @cloud_file.id)

    redirect_to action: "show"
  end

  def cancel_downloads
    @cloud_file = CloudFile.find(params[:id])

    @cloud_file.paths.each do |path|
      path.cancel! if path.may_cancel?
    end

    redirect_to action: "show"
  end

  def enqueue_downloads
    @cloud_file = CloudFile.find(params[:id])

    DefaultWorker.perform_async(task: "enqueue_downloads", cloud_file_id: @cloud_file.id)

    redirect_to action: "show"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_cloud_file
    @cloud_file = CloudFile.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def cloud_file_params
    params.require(:cloud_file).permit(:filename, :status, :original_link, :directory, :remote_created_at)
  end

  def add_params
    params.require(:link)
  end
end

app/helpers/cloud_files_helper.rb
module CloudFilesHelper
end

app/views/cloud_files/_form.html.erb
<%= form_with(model: cloud_file) do |form| %>
  <% if cloud_file.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cloud_file.errors.count, "error") %> prohibited this cloud_file from being saved:</h2>

      <ul>
        <% cloud_file.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :filename %>
    <%= form.text_field :filename %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.number_field :status %>
  </div>

  <div class="field">
    <%= form.label :original_link %>
    <%= form.text_field :original_link %>
  </div>

  <div class="field">
    <%= form.label :directory %>
    <%= form.check_box :directory %>
  </div>

  <div class="field">
    <%= form.label :remote_created_at %>
    <%= form.datetime_select :remote_created_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cloud_files/edit.html.erb
<h1>Editing Cloud File</h1>

<%= render 'form', cloud_file: @cloud_file %>

<%= link_to 'Show', @cloud_file %> |
<%= link_to 'Back', cloud_files_path %>

app/views/cloud_files/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cloud Files</h1>

<%= render "shared/header" %>

<div class="card bg-light p-3">
  <div class="container-fluid">
    <div class="row">
      <div class="col">
        <%= form_with url: :cloud_files_add do |form| %>
          <%= form.label :link, "Add magnet or torrent link" %>
          <%= form.text_field :link %>
          <%= form.submit "Add" %>
        <% end %>
      </div>

      <div class="col">
        <% if params[:show_deleted] %>
          <%= link_to "Hide deleted", cloud_files_path, class: "link-secondary" %>
        <% else %>
          <%= link_to "Show deleted", cloud_files_path(show_deleted: true), class: "link-secondary" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="p-3">
  <%= turbo_frame_tag @cloud_files do %>
    <%= render "shared/cloud_files" %>
  <% end %>
</div>

app/views/cloud_files/new.html.erb
<h1>New Cloud File</h1>

<%= render 'form', cloud_file: @cloud_file %>

<%= link_to 'Back', cloud_files_path %>

app/views/cloud_files/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid">
  <h3><%= @cloud_file.filename %></h3>

  <%= render "shared/cloud_file"%>

  <%= button_to 'Sync', sync_cloud_files_path(@cloud_file), method: :post %>

  <%= render "shared/path_list" %>

  <%= link_to 'Back', cloud_files_path, class: "link-secondary" %>
</div>